BSWebApp/BSWebApp/Models/ViewModels/AddShopOffersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using BS.DB.EntityFW;

namespace BSWebApp.Models.ViewModels
{
    public class AddShopOffersViewModel
    {
        public TBL_ShopOffers ShopOffer { get; set; }
        public List<TBL_OfferOnProducts> OfferonProducts { get; set; }
        public string SelectedProductJson { get; set; }
    }

    public class SelectedProductList
    {
        public string IsSelected { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
    }
}

BSWebApp/BSWebApp/Controllers/ShopOffersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using BS.DB.EntityFW;
using BSWebApp.Common;
using BSWebApp.Models.Common;
using BSWebApp.Models.ViewModels;

namespace BSWebApp.Controllers
{
    public class ShopOffersController : BaseController
    {
      

        // GET: ShopOffers/Create
        public ActionResult AddShopOffer()
        {
            FillViewDatasForAddShopOffers();
            return View();
        }

        public ActionResult ViewShopOffers()
        {
            FillViewDatasForAddShopOffers();
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddShopOffer(AddShopOffersViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var client = new HttpClient())
                    {
                        var currentUserId = CommonSafeConvert.ToInt(Session["CurrentUserID"]);
                        model.ShopOffer.ShopID = GetCurrentShopId();
                        model.ShopOffer.CreatedBy = currentUserId;
                        
                        var selectedProductList = new JavaScriptSerializer().Deserialize<List<SelectedProductList>>(model.SelectedProductJson);
                        model.OfferonProducts= new List<TBL_OfferOnProducts>();
                        selectedProductList.ForEach(x=> model.OfferonProducts.Add(new TBL_OfferOnProducts() { ProductID = x.ProductID, OfferID = model.ShopOffer.OfferID}));

                        client.BaseAddress = new Uri(WebAppConfig.GetConfigValue("WebAPIUrl"));
                        client.DefaultRequestHeaders.Accept.Clear();
                        client.DefaultRequestHeaders.Accept.Add(
                            new MediaTypeWithQualityHeaderValue("application/json"));
                        var response = await client.PostAsJsonAsync("/api/shopoffers/PostNewShopOffers", model);

                       // var response = new CommonAjaxCallToWebAPI().AjaxPost(@"/api/shopoffers/PostNewShopOffers", model);

                        if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        {

                            var rslt = await response.Content.ReadAsStringAsync();
                            var reslt = new JavaScriptSerializer().Deserialize<BSEntityFramework_ResultType>(rslt);
                            if (reslt.Result == BSResult.FailForValidation)
                            {
                                foreach (var valerr in reslt.EntityValidationException)
                                    ModelState.AddModelError("BS Errors", valerr);
                            }
                            else
                            {
                                ModelState.AddModelError("BS Errors", reslt.ResultMsg);
                            }
                            //return reslt;
                            FillViewDatasForAddShopOffers();
                            return View();
                        }
                        else
                        {
                            FillViewDatasForAddShopOffers();
                            return View();
                        }
                    }


                }
                FillViewDatasForAddShopOffers();
                return View("AddShopOffer", model);
            }
            catch (Exception ex)
            {
                FillViewDatasForAddShopOffers();
                return View();
            }
        }


        private void FillViewDatasForAddShopOffers()
        {
            var shopId = GetCurrentShopId();
            Dictionary<string, List<SelectListItem>> selectListData = new Dictionary<string, List<SelectListItem>>();
            var brandList = GetShopBrandList(shopId);
            selectListData.Add("ShopBrandList", brandList);
            ViewData["SelectListData"] = selectListData;

            ViewData["SpGnd"] = BSSecurityEncryption.Encrypt(Convert.ToString(shopId),
                WebAppConfig.GetConfigValue("BSGnd"));
        }
       

        [HttpGet]
       public JsonResult GetProductList(string bsGnd ="", string brand = "", string sidx = "ProductName", string sord = "asc", int rows = 3, int page = 1)
        {
        
            try
            {
                var currentShopId =
                    BSSecurityEncryption.Decrypt(bsGnd, WebAppConfig.GetConfigValue("BSGnd"));
                var param = new List<KeyValuePair<string, string>>
                {
                new KeyValuePair<string, string>("shopId", currentShopId),
                new KeyValuePair<string, string>("sortColumnName", sidx),
                    new KeyValuePair<string, string>("sortOrder", sord),
                    new KeyValuePair<string, string>("pageSize", Convert.ToString(rows)),
                    new KeyValuePair<string, string>("currentPage", Convert.ToString(page)),
                    new KeyValuePair<string, string>("brand", Convert.ToString(brand))
                };

                var data= new CommonAjaxCallToWebAPI().AjaxGet(@"/api/product/GetProductList", param, Convert.ToString(Session["BSWebApiToken"]));
                //  return Json(data, JsonRequestBehavior.AllowGet);

                var jqGridData = new JqGridType()
                {
                    Data = data,
                    Page = "1",
                    PageSize = "3", // u can change this !
                    SortColumn = "1",
                    SortOrder = "asc"
                };

                return Json(jqGridData, JsonRequestBehavior.AllowGet);

            }
            catch
            {
                return null;
            }
        }


        [HttpGet]
        public JsonResult GetOffersList(string offerShortDetails = "", string offerStartDate = "", string offerEndDate = "", string offerOnBrand = "",
              string isOfferOnProduct = null,
              string isActive = null,
              string bsGnd = "",
              string sord = "asc", int rows = 3, int page = 1, string sidx = "OfferID")
        {

            try
            {
                var currentShopId =
                    BSSecurityEncryption.Decrypt(bsGnd, WebAppConfig.GetConfigValue("BSGnd"));
                var param = new List<KeyValuePair<string, string>>
                {
                    new KeyValuePair<string, string>("offerShortDetails", offerShortDetails),
                    new KeyValuePair<string, string>("offerStartDate", offerStartDate),
                    new KeyValuePair<string, string>("offerEndDate", offerEndDate),
                    new KeyValuePair<string, string>("offerOnBrand", offerOnBrand),
                    new KeyValuePair<string, string>("isOfferOnProduct", isOfferOnProduct),
                    new KeyValuePair<string, string>("isActive", isActive),
                    new KeyValuePair<string, string>("shopId", currentShopId),
                    new KeyValuePair<string, string>("sortColumnName", sidx),
                    new KeyValuePair<string, string>("sortOrder", sord),
                    new KeyValuePair<string, string>("pageSize", Convert.ToString(rows)),
                    new KeyValuePair<string, string>("currentPage", Convert.ToString(page)),

                };

                var data = new CommonAjaxCallToWebAPI().AjaxGet(@"api/shopoffers/GetShopOffersListView", param
                    , Convert.ToString(Session["BSWebApiToken"]));
                //  return Json(data, JsonRequestBehavior.AllowGet);

                var jqGridData = new JqGridType()
                {
                    Data = data,
                    Page = "1",
                    PageSize = "3", // u can change this !
                    SortColumn = "1",
                    SortOrder = "asc"
                };

                return Json(jqGridData, JsonRequestBehavior.AllowGet);

            }
            catch
            {
                return null;
            }
        }

        [HttpGet]

        public string GetOfferImage(string id, string bsGnd)
        {
            var param = new List<KeyValuePair<string, string>>
            {
                new KeyValuePair<string, string>("offerId", id),
                new KeyValuePair<string, string>("shopId", "0")
            };
            var reslt = new CommonAjaxCallToWebAPI().AjaxGet(@"/api/shopoffers/GetOfferImage", param, Convert.ToString(Session["BSWebApiToken"]));
            var prodImageDtls = new JavaScriptSerializer().Deserialize<ImageDetails>(reslt);
            return "<img id= 'Offerid" + id + "img' name='" + prodImageDtls.ImgID + "' style='display: block; margin: 0 auto; height: 200px; width: 200px;' src = " + prodImageDtls.ImgData + " />";
        }



        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> EditOffer(ProductUpdateForm formDATA)
        {
            var ProductDetails = new JavaScriptSerializer().Deserialize<TBL_Products>(formDATA.ProductDetails);
            UserDetails currentUser = GetCurrentUserDetails();
            AddProductViewModel model = new AddProductViewModel();
            model.ProductDetails = ProductDetails;
            if (formDATA.file != null)
            {
                model.ProductImages = new List<TBL_ProductImages>();
                model.ProductImages.Add(new TBL_ProductImages()
                {
                    ImageID = CommonSafeConvert.ToInt(formDATA.imgId),
                    ProductID = ProductDetails.ProductID,
                    UpdatedBy = currentUser.UserId,

BSWebApp/BSWebApp/Views/ShopOffers/AddShopOffer.cshtml
@using BSWebApp.Common
@model BSWebApp.Models.ViewModels.AddShopOffersViewModel

@{
    ViewBag.Title = "AddShopOffer";
   // Layout = null;
    var selectListData = ViewData["SelectListData"] as Dictionary<string, List<SelectListItem>>;

}
@*<link href="~/Content/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/Scripts/DataTableJS/jquery.dataTables.min.js"></script>*@
<script>
    var BSGnd = '@Convert.ToString(ViewData["SpGnd"])';
</script>
<script src="~/Scripts/Client/AddShopOffer/AddShopOfferScript.js"></script>



@using (Html.BeginForm("AddShopOffer", "ShopOffers"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="alert alert-danger">
            
            <strong> @Html.ValidationSummary(false, null)</strong>
            
            <strong> @Html.CustomValidationSummary(true)</strong>
        </div>
        <h3>Shop Offers</h3>
        <hr />

        <div class="form-group">
            <div class="col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1">
                @Html.LabelFor(model => model.ShopOffer.OfferShortText, htmlAttributes: new {@class = "label PL10 LH30 control-label"})
            </div>
            <div class="col-lg-3 col-md-3">
                @Html.EditorFor(model => model.ShopOffer.OfferShortText, new { htmlAttributes = new { @class = "form-control", Placeholder=@Html.DisplayNameFor(name=>name.ShopOffer.OfferShortText)} })
                @Html.ValidationMessageFor(model => model.ShopOffer.OfferShortText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1">
                @Html.LabelFor(model => model.ShopOffer.OfferStartDate
                    , htmlAttributes: new { @class = "label PL10 LH30 control-label" })
            </div>
            <div class="col-lg-3 col-md-3">
                @Html.EditorFor(model => model.ShopOffer.OfferStartDate, new { htmlAttributes = new { @class = "form-control", Placeholder = @Html.DisplayNameFor(name => name.ShopOffer.OfferStartDate) } })
                @Html.ValidationMessageFor(model => model.ShopOffer.OfferStartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1">
                @Html.LabelFor(model => model.ShopOffer.OfferEndDate, htmlAttributes: new { @class = "label PL10 LH30 control-label" })
            </div>
            <div class="col-lg-3 col-md-3">
                @Html.EditorFor(model => model.ShopOffer.OfferEndDate, new { htmlAttributes = new { @class = "form-control", Placeholder = @Html.DisplayNameFor(name => name.ShopOffer.OfferEndDate) } })
                @Html.ValidationMessageFor(model => model.ShopOffer.OfferEndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1">
                @Html.LabelFor(model => model.ShopOffer.OfferOnBrand, htmlAttributes: new { @class = "label PL10 LH30 control-label" })
            </div>
            <div class="col-lg-3 col-md-3">
                @if (selectListData["ShopBrandList"] != null)
                {
                    @Html.DropDownListFor(model => model.ShopOffer.OfferOnBrand, selectListData["ShopBrandList"],  new {id= "shopOffers_Brand", @class = "form-control", Placeholder = @Html.DisplayNameFor(name => name.ShopOffer.OfferOnBrand) } )
                }
                else
                {
                    @Html.DropDownListFor(model => model.ShopOffer.OfferOnBrand, new List<SelectListItem>() { new SelectListItem() { Text = "Select" } }, new { id="shopOffers_Brand", @class = "form-control", Placeholder = @Html.DisplayNameFor(name => name.ShopOffer.OfferOnBrand) })
                }
                @Html.ValidationMessageFor(model => model.ShopOffer.OfferOnBrand, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            <div class="col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1">
                @Html.LabelFor(model => model.ShopOffer.IsOfferOnProducts, htmlAttributes: new { @class = "label PL10 LH30 control-label" })
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ShopOffer.IsOfferOnProducts, new { htmlAttributes = new { id = "ShopOffer_chkIsOfferOnProducts" }})
                    @Html.ValidationMessageFor(model => model.ShopOffer.IsOfferOnProducts, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1">
                @Html.LabelFor(model => model.ShopOffer.IsActive, htmlAttributes: new { @class = "label PL10 LH30 control-label" })
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ShopOffer.IsActive)
                    @Html.ValidationMessageFor(model => model.ShopOffer.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1">
                @Html.LabelFor(model => model.ShopOffer.OfferDetailText, htmlAttributes: new { @class = "label PL10 LH30 control-label" })
            </div>
            <div class="col-lg-3 col-md-3">
                @Html.TextAreaFor(model => model.ShopOffer.OfferDetailText, new { htmlAttributes = new { @class = "form-control", Placeholder = @Html.DisplayNameFor(name => name.ShopOffer.OfferDetailText), cols = "40", rows = "5" } })
                @Html.ValidationMessageFor(model => model.ShopOffer.OfferDetailText, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group" id="divProductGrid">
            <div class="col-sm-6">
                <table id="Product_grid"></table>
                <div id="gridPager"></div>
            </div>
            <div class="col-sm-6">
                <table id="SelectedProduct_grid"></table>
                <div id="SelectedgridPager"></div>
            </div>
        </div>
        <div>
        
            @Html.EditorFor(model => model.SelectedProductJson, new { htmlAttributes = new { id = "ShopOffer_hidselprodList",style="display:none;" } })
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnSumbit_AddOffer" value="Create" class="btn btn-sm btn-primary"/>
            </div>
        </div>
    </div>

    
}






    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }




BSWebApp/BSWebApp/Views/ShopOffers/ViewShopOffers.cshtml
@using BSWebApp.Common
@model BSWebApp.Models.ViewModels.AddShopOffersViewModel

@{
    ViewBag.Title = "Shop Offers";
    // Layout = null;
    var selectListData = ViewData["SelectListData"] as Dictionary<string, List<SelectListItem>>;

}
<script src="~/Scripts/Client/BSCommonScript.js"></script>
<script src="~/Scripts/Client/ViewShopOffers/ViewShopOffers.js"></script>
<script>
    var BSGnd = '@Convert.ToString(ViewData["SpGnd"])';
</script>


    <div class="row">
    <div class="col-sm-12">
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <div class="alert alert-danger">

                <strong> @Html.ValidationSummary(false, null)</strong>

                <strong> @Html.CustomValidationSummary(true)</strong>
            </div>
            <h3>Search Products</h3>
            <hr />
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1">
                        @Html.LabelFor(model => model.ShopOffer.OfferShortText, htmlAttributes: new { @class = "label PL10 LH30 control-label" })
                    </div>
                    <div class="col-lg-5 col-md-5">
                        @Html.EditorFor(model => model.ShopOffer.OfferShortText, new { htmlAttributes = new { id= "vwofferShortDetails", @class = "form-control", Placeholder = @Html.DisplayNameFor(name => name.ShopOffer.OfferShortText) } })
                        @Html.ValidationMessageFor(model => model.ShopOffer.OfferShortText, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1">
                        @Html.LabelFor(model => model.ShopOffer.OfferStartDate
                    , htmlAttributes: new { @class = "label PL10 LH30 control-label" })
                    </div>
                    <div class="col-lg-5 col-md-5">
                        @Html.EditorFor(model => model.ShopOffer.OfferStartDate, new { htmlAttributes = new { id = "vwofferStartDate", @class = "form-control", Placeholder = @Html.DisplayNameFor(name => name.ShopOffer.OfferStartDate) } })
                        @Html.ValidationMessageFor(model => model.ShopOffer.OfferStartDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1">
                        @Html.LabelFor(model => model.ShopOffer.OfferEndDate, htmlAttributes: new { @class = "label PL10 LH30 control-label" })
                    </div>
                    <div class="col-lg-5 col-md-5">
                        @Html.EditorFor(model => model.ShopOffer.OfferEndDate, new { htmlAttributes = new { id = "vwofferEndDate", @class = "form-control", Placeholder = @Html.DisplayNameFor(name => name.ShopOffer.OfferEndDate) } })
                        @Html.ValidationMessageFor(model => model.ShopOffer.OfferEndDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1">

                    </div> <div class="col-lg-5 col-md-5">
                       
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1">
                        @Html.LabelFor(model => model.ShopOffer.OfferOnBrand, htmlAttributes: new { @class = "label PL10 LH30 control-label" })
                    </div> <div class="col-lg-5 col-md-5">
                        <div class="checkbox">
                            @if (selectListData["ShopBrandList"] != null)
                {
                                @Html.DropDownListFor(model => model.ShopOffer.OfferOnBrand, selectListData["ShopBrandList"], new { id = "vwofferOnBrand", @class = "form-control", Placeholder = @Html.DisplayNameFor(name => name.ShopOffer.OfferOnBrand) })
                }
                else
                {
                                @Html.DropDownListFor(model => model.ShopOffer.OfferOnBrand, new List<SelectListItem>() { new SelectListItem() { Text = "Select" } }, new { id = "vwofferOnBrand", @class = "form-control", Placeholder = @Html.DisplayNameFor(name => name.ShopOffer.OfferOnBrand) })
                }
                            @Html.ValidationMessageFor(model => model.ShopOffer.OfferOnBrand, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1">
                        @Html.LabelFor(model => model.ShopOffer.IsOfferOnProducts, htmlAttributes: new { @class = "label PL10 LH30 control-label" })
                    </div>
                    <div class="col-lg-5 col-md-5">
                        @Html.DropDownList("vwShopOfferIsOfferonBrand", new List<SelectListItem>()
                        {
                            new SelectListItem() {Text = "All", Value = ""},
                            new SelectListItem() {Text = "True", Value = "True"},
                            new SelectListItem() {Text = "False", Value = "False"}
                        }, new { @class = "form-control"})
                        @*@Html.EditorFor(model => model.ShopOffer.IsOfferOnProducts, new { htmlAttributes = new { id = "vwIsOfferOnProducts" } })
                        @Html.ValidationMessageFor(model => model.ShopOffer.IsOfferOnProducts, "", new { @class = "text-danger" })*@
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1">
                        @Html.LabelFor(model => model.ShopOffer.IsActive, new { @class = "label PL10 LH30 control-label" })
                    </div>
                    <div class="col-lg-5 col-md-5">
                        @Html.DropDownList("vwShopOfferIsactive", new List<SelectListItem>()
                        {
                            new SelectListItem() {Text = "All", Value = ""},
                            new SelectListItem() {Text = "True", Value = "True"},
                            new SelectListItem() {Text = "False", Value = "False"}
                        }, new { @class = "form-control" })
                            @*@Html.EditorFor(model => model.ShopOffer.IsActive, new { htmlAttributes= new {Id = "vwisActive", @class = "form-control"}})
                           @Html.ValidationMessageFor(model => model.ShopOffer.IsActive, "", new {  @class = "text-danger" })*@
                        
                    </div>
                </div>
            </div>

        </div>


        @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnSumbit_AddOffer" value="Create" class="btn btn-sm btn-primary" />
            </div>
        </div>*@
        
        <div class="form-group">
            <div class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1">

            </div> <div align="right" class="col-lg-5 col-md-5">
                <input type="button" value="Search" id="viewOfferbtnSearch" class="btn btn-sm btn-primary" />
                <input type="button" value="Clear" id="viewOfferbtnClear" class="btn btn-sm btn-primary" />
            </div>
        </div>
    </div>

</div>

<hr />
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1">
                <div id="divShopOffersGrid">
                    <table id="ShopOffers_grid"></table>
                    <div id="offergridPager"></div>
                </div>
            </div>
        </div>
    </div>

</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


